# Generated by Django 4.1.2 on 2023-01-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0002_comentario_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='SIGNATURE',
            field=models.CharField(default='Firma', max_length=100),
        ),
    ]
