# Generated by Django 4.1.2 on 2023-01-18 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0003_comentario_signature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='SIGNATURE',
            new_name='signature',
        ),
    ]
