# Generated by Django 4.1.2 on 2023-01-29 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onetoone', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Restaruante',
            new_name='Restaurant',
        ),
    ]
