# Generated by Django 4.1.2 on 2022-10-09 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos_peli', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='Actor',
        ),
    ]
