# Generated by Django 4.1.2 on 2022-10-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos_peli', '0002_rename_author_actor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Actor',
            new_name='Director',
        ),
        migrations.RenameField(
            model_name='pelicula',
            old_name='author',
            new_name='director',
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='summary',
            field=models.TextField(help_text='Resumen Pelicula ', max_length=100),
        ),
    ]
